"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AutoStake.py']
DATA_FILES = [
    "bs.py", "data/tokens.json", 
    "drivers/chromedriver91-mac",
    "drivers/geckodriver-mac",
    "drivers/chromedriver92-mac64",
    "drivers/chromedriver91-macm1",
    "drivers/chromedriver92-macm1"
]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
